# Generated by Django 3.2.20 on 2023-08-28 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bimapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesperson',
            name='user',
        ),
    ]
