# Generated by Django 3.2.20 on 2023-08-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bimapi', '0002_remove_salesperson_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='salesperson',
        ),
    ]
