# Generated by Django 3.2.20 on 2023-08-29 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bimapi', '0003_remove_client_salesperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='bimapi.client'),
        ),
    ]
