# Generated by Django 3.2.20 on 2023-09-07 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bimapi', '0006_client_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='user',
            new_name='agent',
        ),
    ]
